# Generated by Django 3.2.7 on 2021-10-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20211025_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='edit_mode',
            field=models.BooleanField(default=False),
        ),
    ]
